export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
export const CHANGE_COLOR = "CHANGE_COLOR";

export const REQUEST_USERS_PENDING = "REQUEST_USERS_PENDING";
export const REQUEST_USERS_SUCCES = "REQUEST_USERS_SUCCES";
export const REQUEST_USERS_FAILED = "REQUEST_USERS_FAILED";

export const REQUEST_POSTS_PENDING = "REQUEST_POSTS_PENDING";
export const REQUEST_POSTS_SUCCES = "REQUEST_POSTS_SUCCES";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";

export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
export const CHANGE_CONTENT = "CHANGE_CONTENT";

export const INVALID_DATA = "INVALID_DATA";
